before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - skip: true

dockers:
  - image_templates:
    - ukrocks007/fluent-bit-clickhouse:{{ .Tag }}
    extra_files:
    - go.mod
    - go.sum
    - main.go
    - out_clickhouse.go
    - pkg

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
