version: "3"

networks:
  hermes:

services:
  fluentd:
    build: ./
    volumes:
      - ./fluentd/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "8888:8888"
      - "2020:2020"
    networks:
      - hermes

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
      - ./clickhouse_config/config.xml:/etc/clickhouse-server/config.xml
    networks:
      - hermes